[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
super_txn = "superB6bzm82y1To5rRaMr7KmqkLNVnCUGwUBemtJV3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/super-txn.ts"